language: c

matrix:
  include:

    # Build for 64-bit Linux without profiling enabled
    - os: linux
      dist: bionic
      sudo: required
      env: CONFIGFLAGS="CFLAGS=-m64 --enable-cuckoo --enable-magic --enable-pb-tests --enable-address-sanitizer"
      # The certificate for scan.coverity.com is too new and is not recognized by
      # wget. This command adds the certificate to /etc/ssl/certs/ca-certificates.crt
      # See: https://github.com/travis-ci/travis-ci/issues/6142
      before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      install: |
        sudo apt-get update
        sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libjansson-dev \
            libmagic-dev \
            libssl-dev  \
            protobuf-compiler \
            protobuf-c-compiler \
            libprotobuf-c-dev

    # Build for 64-bit Linux with profiling enabled
    - os: linux
      dist: bionic
      sudo: required
      env: CONFIGFLAGS="CFLAGS=-m64 --enable-cuckoo --enable-magic --enable-pb-tests -enable-address-sanitizer --enable-profiling"
      install: |
        sudo apt-get update
        sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libjansson-dev \
            libmagic-dev \
            libssl-dev  \
            protobuf-compiler \
            protobuf-c-compiler \
            libprotobuf-c-dev

before_script: ./bootstrap.sh

script: |
  rvm get head  # Workaround for Travis CI issue https://github.com/travis-ci/travis-ci/issues/6307
  set -e
  unset CC # A pre-set CC overrides --host settings.
  ./configure $CONFIGFLAGS
  make clean && make
  case "$CONFIGFLAGS" in
    *--host=*mingw*) ;;
    *) make check ;;
  esac

after_failure: if [ -e test-suite.log ]; then cat test-suite.log; fi

addons:
  apt:
    packages:
      - ca-certificates
